# Generated by Django 4.2.5 on 2023-10-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DietList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_category",
                    models.CharField(
                        choices=[
                            ("breakfast", "아침"),
                            ("lunch", "점심"),
                            ("dinner", "저녁"),
                            ("snack", "간식"),
                            ("night_snack", "야식"),
                            ("drink", "음료"),
                        ],
                        max_length=30,
                    ),
                ),
                ("meal_calorie", models.FloatField()),
                ("daily_review", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SelectedDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("food_name", models.CharField(max_length=250)),
                ("food_calorie", models.FloatField()),
                ("food_gram", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuantityMultiple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("food_quantity", models.PositiveIntegerField(default=1)),
                (
                    "diet_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diets.dietlist"
                    ),
                ),
                (
                    "selected_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.selecteddiet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dietlist",
            name="selected_diet",
            field=models.ManyToManyField(
                related_name="diets",
                through="diets.QuantityMultiple",
                to="diets.selecteddiet",
            ),
        ),
    ]
