# Generated by Django 4.2.5 on 2023-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0003_quantitymultiple_multipled_food_calorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantitymultiple",
            name="food_quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
