# Generated by Django 4.2.5 on 2023-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0004_alter_quantitymultiple_food_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantitymultiple",
            name="multipled_food_calorie",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="quantitymultiple",
            name="multipled_food_gram",
            field=models.FloatField(null=True),
        ),
    ]
