# Generated by Django 4.2.5 on 2023-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0007_remove_quantitymultiple_multipled_food_calorie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietlist",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="dietlist",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="quantitymultiple",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="quantitymultiple",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="quantitymultiple",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="selecteddiet",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="selecteddiet",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="selecteddiet",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="dietlist",
            name="created_date",
            field=models.DateField(),
        ),
    ]
