# Generated by Django 4.2.5 on 2023-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0009_alter_dietlist_meal_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selecteddiet",
            name="food_name",
            field=models.CharField(max_length=120),
        ),
    ]
